dist:
  name: otelcol-gestalt
  description: Basic OTel Collector for Gestalt
  output_path: .

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.144.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.144.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.144.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.144.0

providers:
  - gomod:
      go.opentelemetry.io/collector/confmap/provider/envprovider v1.48.0
  - gomod:
      go.opentelemetry.io/collector/confmap/provider/fileprovider v1.48.0
  - gomod:
      go.opentelemetry.io/collector/confmap/provider/httpprovider v1.48.0
  # - gomod:
  #     go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.48.0
