name = "Architect"
shell = "copilot"
cli_type = "copilot"
prompt = ["coder", "architect"]
skills = ["terminal-navigation"]
llm_model = "claude-sonnet-4.5"

[cli_config]
# model = "gpt-5" # values: claude-sonnet-4.5 | claude-sonnet-4 | claude-haiku-4.5 | gpt-5
# allow_all_tools = true # values: true | false
# disable_builtin_mcps = true # values: true | false
